### ISSUE TITLE
Tapping the date select box brings up an unclosable box with no content

### ISSUE THREAD

**Issue by jononon** [HWComputerScience/iHW-iOS#2]
The only way to close the box is to close the app and get rid of it in multitasking. This bug has been around for awhile.
![img_7198](https://cloud.githubusercontent.com/assets/5778251/4894364/64f86f5e-63d1-11e4-89a2-5f33b75d96f8.PNG)

**Comment by jburns20** [comment]
Did this ever get fixed in the main repo?

**Comment by jononon** [comment]
I'm pretty sure the main is fixed.
