### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by jmfieldman** [HWComputerScience/iHW-iOS#8]
The current state of the repo cannot be built.  Compile error:

error: /Users/jasonfieldman/Downloads/iHW-iOS-master/images/link.png: No such file or directory

Same error with link@2x.png!

**Comment by jononon** [comment]
Perhaps we want to consider something like https://travis-ci.org which checks if projects can build before merges.

**Comment by jmfieldman** [comment]
Or even just clean/build a project before you check in? :P

**Comment by jmfieldman** [comment]
This commit broke the images in the iOS build: https://github.com/HWComputerScience/iHW-iOS/commit/0895016dea2955168de009b7a1059291763866b6 - someone needs to tend to this.

**Comment by jmfieldman** [comment]
fixed this by adding the resources submodule to iHW-iOS
